### ISSUE TITLE
使用过程中出现了个错误直接退出了

### ISSUE THREAD

**Issue by Geek-007** [leo8916/wxhub#3]
![image](https://user-images.githubusercontent.com/25733662/51293955-dcc0c100-1a4b-11e9-8606-912826440280.png)

**Comment by leo8916** [comment]
这是错误是因为 在选择公众号编号(只有一条)时, 你输入了2号索引导致越界了... 这个只是未做保护, 并不是bug. 后面的优化中提交中会进行越界保护.
